### ISSUE TITLE
Error: no suitable method found for newSimpleInstance line 213

### ISSUE THREAD

**Issue by AravinthVelusamy** [PavanKumarPatruni/custom-video-player#1]
error: no suitable method found for newSimpleInstance(DefaultRenderersFactory,DefaultTrackSelector,DefaultLoadControl)
method ExoPlayerFactory.newSimpleInstance(Context,TrackSelector,LoadControl) is not applicable
(argument mismatch; DefaultRenderersFactory cannot be converted to Context)
method ExoPlayerFactory.newSimpleInstance(Context,RenderersFactory,TrackSelector) is not applicable
(argument mismatch; DefaultRenderersFactory cannot be converted to Context)

**Comment by pavankumar-patruni** [comment]
Please try now and let me know
